# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/maurits/Projects/Baseflow/Internal/DID/adafruit-motor-hat-cpp-library

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/maurits/Projects/Baseflow/Internal/DID/adafruit-motor-hat-cpp-library

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maurits/Projects/Baseflow/Internal/DID/adafruit-motor-hat-cpp-library/CMakeFiles /home/maurits/Projects/Baseflow/Internal/DID/adafruit-motor-hat-cpp-library//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maurits/Projects/Baseflow/Internal/DID/adafruit-motor-hat-cpp-library/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named AdafruitMotor

# Build rule for target.
AdafruitMotor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 AdafruitMotor
.PHONY : AdafruitMotor

# fast build rule for target.
AdafruitMotor/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/build
.PHONY : AdafruitMotor/fast

CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.o: CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

.PHONY : CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.o

# target to build an object file
CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.o
.PHONY : CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.o

CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.i: CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

.PHONY : CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.i

# target to preprocess a source file
CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.i
.PHONY : CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.i

CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.s: CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

.PHONY : CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.s

# target to generate assembly for a file
CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.s
.PHONY : CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.cpp.s

source/adafruitdcmotor.o: source/adafruitdcmotor.cpp.o

.PHONY : source/adafruitdcmotor.o

# target to build an object file
source/adafruitdcmotor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/source/adafruitdcmotor.cpp.o
.PHONY : source/adafruitdcmotor.cpp.o

source/adafruitdcmotor.i: source/adafruitdcmotor.cpp.i

.PHONY : source/adafruitdcmotor.i

# target to preprocess a source file
source/adafruitdcmotor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/source/adafruitdcmotor.cpp.i
.PHONY : source/adafruitdcmotor.cpp.i

source/adafruitdcmotor.s: source/adafruitdcmotor.cpp.s

.PHONY : source/adafruitdcmotor.s

# target to generate assembly for a file
source/adafruitdcmotor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/source/adafruitdcmotor.cpp.s
.PHONY : source/adafruitdcmotor.cpp.s

source/adafruitmotorhat.o: source/adafruitmotorhat.cpp.o

.PHONY : source/adafruitmotorhat.o

# target to build an object file
source/adafruitmotorhat.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/source/adafruitmotorhat.cpp.o
.PHONY : source/adafruitmotorhat.cpp.o

source/adafruitmotorhat.i: source/adafruitmotorhat.cpp.i

.PHONY : source/adafruitmotorhat.i

# target to preprocess a source file
source/adafruitmotorhat.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/source/adafruitmotorhat.cpp.i
.PHONY : source/adafruitmotorhat.cpp.i

source/adafruitmotorhat.s: source/adafruitmotorhat.cpp.s

.PHONY : source/adafruitmotorhat.s

# target to generate assembly for a file
source/adafruitmotorhat.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/source/adafruitmotorhat.cpp.s
.PHONY : source/adafruitmotorhat.cpp.s

source/adafruitsteppermotor.o: source/adafruitsteppermotor.cpp.o

.PHONY : source/adafruitsteppermotor.o

# target to build an object file
source/adafruitsteppermotor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/source/adafruitsteppermotor.cpp.o
.PHONY : source/adafruitsteppermotor.cpp.o

source/adafruitsteppermotor.i: source/adafruitsteppermotor.cpp.i

.PHONY : source/adafruitsteppermotor.i

# target to preprocess a source file
source/adafruitsteppermotor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/source/adafruitsteppermotor.cpp.i
.PHONY : source/adafruitsteppermotor.cpp.i

source/adafruitsteppermotor.s: source/adafruitsteppermotor.cpp.s

.PHONY : source/adafruitsteppermotor.s

# target to generate assembly for a file
source/adafruitsteppermotor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/source/adafruitsteppermotor.cpp.s
.PHONY : source/adafruitsteppermotor.cpp.s

source/i2cdevice.o: source/i2cdevice.cpp.o

.PHONY : source/i2cdevice.o

# target to build an object file
source/i2cdevice.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/source/i2cdevice.cpp.o
.PHONY : source/i2cdevice.cpp.o

source/i2cdevice.i: source/i2cdevice.cpp.i

.PHONY : source/i2cdevice.i

# target to preprocess a source file
source/i2cdevice.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/source/i2cdevice.cpp.i
.PHONY : source/i2cdevice.cpp.i

source/i2cdevice.s: source/i2cdevice.cpp.s

.PHONY : source/i2cdevice.s

# target to generate assembly for a file
source/i2cdevice.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/source/i2cdevice.cpp.s
.PHONY : source/i2cdevice.cpp.s

source/pwm.o: source/pwm.cpp.o

.PHONY : source/pwm.o

# target to build an object file
source/pwm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/source/pwm.cpp.o
.PHONY : source/pwm.cpp.o

source/pwm.i: source/pwm.cpp.i

.PHONY : source/pwm.i

# target to preprocess a source file
source/pwm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/source/pwm.cpp.i
.PHONY : source/pwm.cpp.i

source/pwm.s: source/pwm.cpp.s

.PHONY : source/pwm.s

# target to generate assembly for a file
source/pwm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/AdafruitMotor.dir/build.make CMakeFiles/AdafruitMotor.dir/source/pwm.cpp.s
.PHONY : source/pwm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... AdafruitMotor"
	@echo "... CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.o"
	@echo "... CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.i"
	@echo "... CMakeFiles/3.18.4/CompilerIdCXX/CMakeCXXCompilerId.s"
	@echo "... source/adafruitdcmotor.o"
	@echo "... source/adafruitdcmotor.i"
	@echo "... source/adafruitdcmotor.s"
	@echo "... source/adafruitmotorhat.o"
	@echo "... source/adafruitmotorhat.i"
	@echo "... source/adafruitmotorhat.s"
	@echo "... source/adafruitsteppermotor.o"
	@echo "... source/adafruitsteppermotor.i"
	@echo "... source/adafruitsteppermotor.s"
	@echo "... source/i2cdevice.o"
	@echo "... source/i2cdevice.i"
	@echo "... source/i2cdevice.s"
	@echo "... source/pwm.o"
	@echo "... source/pwm.i"
	@echo "... source/pwm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

